### PR TITLE
Small changes to using_manifolds.md docs

### PR DESCRIPTION
**Pull request by mateuszbaran**
I've made a few small changes to `using_manifold.md` -- let me know what you think :slightly_smiling_face:

### CODE REVIEW

**Review by dehann — APPROVED** [review]
Ah, that's awesome thanks!

**Comment by dehann** [comment]
I take it from the few changes that you don't have terrible disagreement on the content of the overall page :-)  Style is more lighthearted, to give readers an opportunity to pick their depth and maybe come back for a second round to dive deeper.  I also want this page to bring more people to the JuliaManifolds ecosystem!

----

Totally independent of all the code stuff here, I really wish I had more manifolds in my earlier math training -- I've had to parse textbooks and online resources independently just to figure out what terms I need to be looking for.  What I'm trying to do beyond making the code easy to use and useful, is to make the documentation approachable and give people easy places to connect rather than be overwhelmed on day 1.

**Comment by mateuszbaran** [comment]
> I take it from the few changes that you don't have terrible disagreement on the content of the overall page :-) Style is more lighthearted, to give readers an opportunity to pick their depth and maybe come back for a second round to dive deeper. I also want this page to bring more people to the JuliaManifolds ecosystem!

The content is really good. I always struggle with writing more approachable descriptions of manifolds so I appreciate your text :slightly_smiling_face: .

As @kellertuer noted in [his comment](https://github.com/JuliaManifolds/Manifolds.jl/pull/355#issuecomment-1088476581), there are some differences in notation between this text and JuliaManifolds. Our notation is based on what is most common in manifolds-based optimisation literature, and is also very close to some robotics texts, for example micro Lie theory. Do you want to keep a different notation here?

> Totally independent of all the code stuff here, I really wish I had more manifolds in my earlier math training -- I've had to parse textbooks and online resources independently just to figure out what terms I need to be looking for. What I'm trying to do beyond making the code easy to use and useful, is to make the documentation approachable and give people easy places to connect rather than be overwhelmed on day 1.

I think this is very valuable. Manifolds.jl currently has issues with discoverability of certain capabilities. I think it will be much easier if you just ask me or Ronny how to do something, so you would know much faster what you need to be looking for :slightly_smiling_face: . Another benefit is that by knowing what you need we can discover shortcomings of our API and fix them. I definitely want to make Manifolds.jl suitable for robotics applications. When developing Manifolds.jl I take into account the contents of the micro Lie theory paper. For example the ongoing work on manifold automatic differentiation should significantly expand what people can do without working with all this manual chaining of Jacobians but I'm not sure how to communicate this, or what examples would be interesting.

**Comment by Affie** [comment]
> manifold automatic differentiation

I'm looking forward to this. I decided to wait for AD in manifolds and not do it the jacobian way for the updates that will come soon to the solver.

**Comment by mateuszbaran** [comment]
> I'm looking forward to this. I decided to wait for AD in manifolds and not do it the jacobian way for the updates that will come soon to the solver.

Great! We are currently polishing and extending our AD code, as well as preparing some examples of usage. When this is done, we will publish the code. I'm definitely interested in supporting your use cases :slightly_smiling_face: .

**Pull request merged**
