### PR TITLE
Bayes tree docs discussion

### PR DESCRIPTION
**Pull request by dehann**

### CODE REVIEW

**Comment by dehann** [comment]
hi @tonioteran, perhaps i could bump on this PR -- if you had any text or visuals that you dont mind sharing in the docs?  Should be simple matter of just adding to the markdown file.  I store images on RoME gist and then copy the link:
https://gist.github.com/dehann/5f943d833f5fb06f4e00a2f4fb9f945a

**Comment by tonioteran** [comment]
hey @dehann, how do I upload more images to your gist. I tried forking and then cloning, but I can't figure out how to add my images.

**Comment by dehann** [comment]
Oh just drag a drop images into the next comment box on the gist.  Github will then upload for you and give back a link in the comment box

**Comment by tonioteran** [comment]
alright, let me know what you think!

**Comment by dehann** [comment]
Looks great thanks! going to merge

**Pull request merged**
